import {
  ISO3166_2letter_country_codes,
  ISO639_1LanguageCodeType,
} from "../types/common/common.types";

export const CountryCode2letter2Name: Record<
  ISO3166_2letter_country_codes,
  string
> = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AG: "Antigua & Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia & Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  VG: "British Virgin Islands",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  IC: "Canary Islands",
  CV: "Cape Verde",
  BQ: "Caribbean Netherlands",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  EA: "Ceuta & Melilla",
  TD: "Chad",
  CL: "Chile",
  CN: "China mainland",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo - Brazzaville",
  CD: "Congo - Kinshasa",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d’Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DG: "Diego Garcia",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GW: "Guinea-Bissau",
  GN: "Guinea",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  XK: "Kosovo",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar (Burma)",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  KP: "North Korea",
  MK: "North Macedonia",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territories",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn Islands",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  WS: "Samoa",
  SM: "San Marino",
  ST: "São Tomé & Príncipe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  BL: "St. Barthélemy",
  SH: "St. Helena",
  KN: "St. Kitts & Nevis",
  LC: "St. Lucia",
  MF: "St. Martin",
  PM: "St. Pierre & Miquelon",
  VC: "St. Vincent & Grenadines",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard & Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad & Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks & Caicos Islands",
  TV: "Tuvalu",
  UM: "U.S. Outlying Islands",
  VI: "U.S. Virgin Islands",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  WF: "Wallis & Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const LanguageCode2Name: Record<ISO639_1LanguageCodeType, string> = {
  af: "Afrikaans",
  agq: "Aghem",
  ak: "Akan",
  am: "Amharic",
  ar: "Arabic",
  arn: "Mapuche",
  as: "Assamese",
  asa: "Asu",
  ast: "Asturian",
  az: "Azerbaijani",
  ba: "Bashkir",
  bas: "Basaa",
  be: "Belarusian",
  bem: "Bemba",
  bez: "Bena",
  bg: "Bulgarian",
  bm: "Bambara",
  bn: "Bangla",
  bo: "Tibetan",
  br: "Breton",
  brx: "Bodo",
  bs: "Bosnian",
  byn: "Blin",
  ca: "Catalan",
  ccp: "Chakma",
  ce: "Chechen",
  ceb: "Cebuano",
  cgg: "Chiga",
  chr: "Cherokee",
  ckb: "Kurdish, Sorani",
  co: "Corsican",
  cs: "Czech",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  dav: "Taita",
  de: "German",
  dje: "Zarma",
  dsb: "Lower Sorbian",
  dua: "Duala",
  dv: "Dhivehi",
  dyo: "Jola-Fonyi",
  dz: "Dzongkha",
  ebu: "Embu",
  ee: "Ewe",
  el: "Greek",
  en: "English",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  ewo: "Ewondo",
  fa: "Persian",
  ff: "Fulah",
  fi: "Finnish",
  fil: "Filipino",
  fo: "Faroese",
  fr: "French",
  fur: "Friulian",
  fy: "Western Frisian",
  ga: "Irish",
  gaa: "Ga",
  gd: "Scottish Gaelic",
  gez: "Geez",
  gl: "Galician",
  gn: "Guarani",
  gsw: "Swiss German",
  gu: "Gujarati",
  guz: "Gusii",
  gv: "Manx",
  ha: "Hausa",
  haw: "Hawaiian",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  hsb: "Upper Sorbian",
  hu: "Hungarian",
  hy: "Armenian",
  id: "Indonesian",
  ig: "Igbo",
  ii: "Sichuan Yi",
  is: "Icelandic",
  it: "Italian",
  iu: "Inuktitut",
  ja: "Japanese",
  jgo: "Ngomba",
  jmc: "Machame",
  jv: "Javanese",
  ka: "Georgian",
  kab: "Kabyle",
  kaj: "Jju",
  kam: "Kamba",
  kcg: "Tyap",
  kde: "Makonde",
  kea: "Kabuverdianu",
  khq: "Koyra Chiini",
  ki: "Kikuyu",
  kk: "Kazakh",
  kkj: "Kako",
  kl: "Kalaallisut",
  kln: "Kalenjin",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  kok: "Konkani",
  kpe: "Kpelle",
  ks: "Kashmiri",
  ksb: "Shambala",
  ksf: "Bafia",
  ksh: "Colognian",
  ku: "Kurdish",
  kw: "Cornish",
  ky: "Kyrgyz",
  lag: "Langi",
  lb: "Luxembourgish",
  lg: "Ganda",
  lkt: "Lakota",
  ln: "Lingala",
  lo: "Lao",
  lrc: "Northern Luri",
  lt: "Lithuanian",
  lu: "Luba-Katanga",
  luo: "Luo",
  luy: "Luyia",
  lv: "Latvian",
  mas: "Masai",
  mer: "Meru",
  mfe: "Morisyen",
  mg: "Malagasy",
  mgh: "Makhuwa-Meetto",
  mgo: "Metaʼ",
  mi: "Maori",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mni: "Manipuri",
  moh: "Mohawk",
  mr: "Marathi",
  ms: "Malay",
  mt: "Maltese",
  mua: "Mundang",
  my: "Burmese",
  myv: "Erzya",
  mzn: "Mazanderani",
  naq: "Nama",
  nb: "Norwegian Bokmål",
  nd: "North Ndebele",
  nds: "Low German",
  ne: "Nepali",
  nl: "Dutch",
  nmg: "Kwasio",
  nn: "Norwegian Nynorsk",
  nnh: "Ngiemboon",
  nqo: "N’Ko",
  nr: "South Ndebele",
  nso: "Northern Sotho",
  nus: "Nuer",
  ny: "Nyanja",
  nyn: "Nyankole",
  oc: "Occitan",
  om: "Oromo",
  or: "Odia",
  os: "Ossetic",
  pa: "Punjabi",
  pl: "Polish",
  ps: "Pashto",
  pt: "Portuguese",
  qu: "Quechua",
  rm: "Romansh",
  rn: "Rundi",
  ro: "Romanian",
  rof: "Rombo",
  ru: "Russian",
  rw: "Kinyarwanda",
  rwk: "Rwa",
  sa: "Sanskrit",
  sah: "Sakha",
  saq: "Samburu",
  sat: "Santali",
  sbp: "Sangu",
  sc: "Sardinian",
  scn: "Sicilian",
  sd: "Sindhi",
  se: "Northern Sami",
  seh: "Sena",
  ses: "Koyraboro Senni",
  sg: "Sango",
  shi: "Tachelhit",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  smn: "Inari Sami",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  ss: "Swati",
  st: "Southern Sotho",
  sv: "Swedish",
  sw: "Swahili",
  syr: "Syriac",
  ta: "Tamil",
  te: "Telugu",
  teo: "Teso",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tig: "Tigre",
  tk: "Turkmen",
  tn: "Tswana",
  to: "Tongan",
  tr: "Turkish",
  trv: "Taroko",
  ts: "Tsonga",
  tt: "Tatar",
  twq: "Tasawaq",
  tzm: "Central Atlas Tamazight",
  ug: "Uyghur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  vai: "Vai",
  ve: "Venda",
  vi: "Vietnamese",
  vun: "Vunjo",
  wa: "Walloon",
  wae: "Walser",
  wal: "Wolaytta",
  wo: "Wolof",
  xh: "Xhosa",
  xog: "Soga",
  yav: "Yangben",
  yo: "Yoruba",
  yue: "Cantonese",
  zgh: "Standard Moroccan Tamazight",
  zh: "Chinese",
  zu: "Zulu",
};
