CREATE TABLE languages (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    `language` CHAR(2) NOT NULL,
    UNIQUE (`language`)
);

CREATE TABLE users (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    email VARCHAR(512) NOT NULL,
    password VARCHAR(512) NOT NULL,
    first_name VARCHAR(256) NOT NULL,
    middle_name VARCHAR(256) NOT NULL,
    last_name VARCHAR(256) NOT NULL,
    username VARCHAR(512) NOT NULL,
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (email),
    UNIQUE (username)
);

CREATE TABLE sessions (
    `session` CHAR(36) CHARACTER SET utf8 PRIMARY KEY NOT NULL COMMENT 'UUID',
    user_id CHAR(36) NOT NULL REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (user_id)
);

CREATE TABLE user_preferred_languages (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id CHAR(36) NOT NULL REFERENCES users(id),
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (user_id, `language`)
);

CREATE TABLE objtxts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    text VARCHAR(1024) NOT NULL,
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`),
    sound_url VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE objects (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    user_id CHAR(36) NOT NULL REFERENCES users(id),
    original_ojbtxt_id INTEGER NOT NULL REFERENCES objtxts(id),
    bbox_ul_x FLOAT,
    bbox_ul_y FLOAT,
    bbox_ll_x FLOAT,
    bbox_ll_y FLOAT,
    bbox_lr_x FLOAT,
    bbox_lr_y FLOAT,
    bbox_ur_x FLOAT,
    bbox_ur_y FLOAT,
    image_url VARCHAR(1024) NOT NULL,
    caption VARCHAR(1024),
    country VARCHAR(512),
    city VARCHAR(512),
    latitude FLOAT,
    longitude FLOAT,
    liked BOOLEAN NOT NULL DEFAULT false,
    num_failures INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (original_ojbtxt_id)
);

CREATE TABLE object_target_objtxts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    object_id CHAR(36) NOT NULL REFERENCES objects(id),
    target_objtxt_id INTEGER NOT NULL REFERENCES objtxts(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (object_id, target_objtxt_id)
);

CREATE TABLE lists (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    `name` VARCHAR(256) NOT NULL,
    icon_name VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (name)
);

CREATE TABLE list_objects (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    list_id CHAR(36) NOT NULL REFERENCES lists(id),
    object_id CHAR(36) NOT NULL REFERENCES objects(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (list_id, object_id)
);
