CREATE TABLE languages (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    `language` CHAR(2) NOT NULL,
    UNIQUE (`language`)
);

CREATE TABLE users (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    email VARCHAR(512) NOT NULL,
    `password` VARCHAR(512) NOT NULL,
    first_name VARCHAR(256) NOT NULL,
    middle_name VARCHAR(256) NOT NULL,
    last_name VARCHAR(256) NOT NULL,
    username VARCHAR(512) NOT NULL,
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`) ON DELETE CASCADE,
    profile_image VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (email),
    UNIQUE (username)
);

CREATE TABLE sessions (
    `session` CHAR(36) CHARACTER SET utf8 PRIMARY KEY NOT NULL COMMENT 'UUID',
    user_id CHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (user_id)
);

CREATE TABLE user_preferred_languages (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id CHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (user_id, `language`),
    INDEX (user_id)
);

CREATE TABLE objtxts (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    text VARCHAR(1024) NOT NULL,
    `language` CHAR(2) NOT NULL REFERENCES languages(`language`) ON DELETE CASCADE,
    sound_url VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE objects (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    user_id CHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    original_ojbtxt_id CHAR(36) NOT NULL REFERENCES objtxts(id) ON DELETE CASCADE ,
    bbox_x FLOAT,
    bbox_y FLOAT,
    bbox_w FLOAT,
    bbox_h FLOAT,
    image_url VARCHAR(1024) NOT NULL,
    caption VARCHAR(1024),
    country VARCHAR(512),
    city VARCHAR(512),
    latitude FLOAT,
    longitude FLOAT,
    liked BOOLEAN NOT NULL DEFAULT false,
    num_failures INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (original_ojbtxt_id),
    INDEX (user_id)
);

CREATE TABLE object_target_objtxts (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    object_id CHAR(36) NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    target_objtxt_id CHAR(36) NOT NULL REFERENCES objtxts(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (object_id, target_objtxt_id),
    INDEX (object_id),
    INDEX (target_objtxt_id)
);

CREATE TABLE lists (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    `name` VARCHAR(256) NOT NULL,
    user_id CHAR(36) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    icon_name VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (name)
);

CREATE TABLE list_objects (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    list_id CHAR(36) NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
    object_id CHAR(36) NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (list_id, object_id),
    INDEX (list_id),
    INDEX (object_id)
);
